translate french strings:
    old "Stable"
    new "Stable"
    old "Guarded"
    new "Surveillance rapprochée"
    old "Concerning"
    new "Préoccupant"
    old "Critical"
    new "Critique"
    old "Decompensating"
    new "Décompensation"
    old "Difficulty: [selected_difficulty]"
    new "Niveau : [selected_difficulty]"
    old "Stability: [stability_view_text()]"
    new "Stabilité : [stability_view_text()]"
    old "Step: [game_state['stepIndex']]"
    new "Étape : [game_state['stepIndex']]"
    old "Labs/ABG: [tr(node['labs'])]"
    new "Bilans/GDS : [tr(node['labs'])]"
    old "Educational only — verify with guidelines."
    new "Éducatif uniquement — vérifier avec les recommandations."
    old "Time: [timer_left]s"
    new "Temps : [timer_left]s"
    old "Case Debrief"
    new "Débriefing du cas"
    old "Return to Main Menu"
    new "Retour au menu principal"
    old "Diagnostics"
    new "Diagnostics"
    old "No validation errors."
    new "Aucune erreur de validation."
    old "Select Case"
    new "Choisir un cas"
    old "Difficulty"
    new "Difficulté"
    old "Selected: [selected_difficulty]"
    new "Sélection : [selected_difficulty]"
    old "Timer: [difficulty_timer_seconds(selected_difficulty)]s"
    new "Minuteur : [difficulty_timer_seconds(selected_difficulty)]s"
    old "Start"
    new "Démarrer"
    old "Back"
    new "Retour"
    old "Settings"
    new "Paramètres"
    old "Leaderboard"
    new "Classement"
    old "Play"
    new "Jouer"
    old "Quit"
    new "Quitter"
    old "English"
    new "English"
    old "Français"
    new "Français"
    old "No runs yet."
    new "Aucune partie enregistrée."
    old "Pick a case first."
    new "Choisissez d'abord un cas."
    old "No case selected."
    new "Aucun cas sélectionné."

    old "Case Library"
    new "Bibliothèque de cas"
    old "Profile"
    new "Profil"
    old "Credits"
    new "Crédits"
    old "Name: [persistent.profile_name]"
    new "Nom : [persistent.profile_name]"
    old "Level: [persistent.level]"
    new "Niveau : [persistent.level]"
    old "XP: [persistent.xp]/[xp_to_next_level(persistent.level)]"
    new "XP : [persistent.xp]/[xp_to_next_level(persistent.level)]"
    old "Diagnostic streak: [persistent.diagnostic_streak]"
    new "Série diagnostique : [persistent.diagnostic_streak]"
    old "Weak areas:"
    new "Axes à renforcer :"
    old "No weak areas tracked yet."
    new "Aucun axe à renforcer pour le moment."
    old "Clinical Dominion MVP"
    new "Clinical Dominion MVP"
    old "Design: Clinical Simulation Team"
    new "Conception : Équipe de simulation clinique"
    old "Engine: Ren'Py"
    new "Moteur : Ren'Py"
